### ISSUE TITLE
insertar la publicidad en la pagina de inicio, como está ahora (y ver si se puede hacer un tutorial para cargarla)

### ISSUE THREAD

**Issue by javierllugany** [gaenseklein/comecuco#10]

**Comment by javierllugany** [comment]
armé el bloque para la publicidad en el frontpage y en layout.css

**Comment by gaenseklein** [comment]
lo hacemos diferente: creamos un formulario en donde los usuarios pueden subir un comercial. 
un comercial obtiene: 
- un imagen de referencia
- una descripcion alternativa (para los que no ven graficos)
- una url adonde refiere el link del comercial (opcional) 
- una fecha de inicio 
- una fecha de fin

si la fecha actual esta dentro de fecha de inicio y fin del comercial se muenstra el comercial.

**Comment by javierllugany** [comment]
armé EDITARpublicidad.html

**Comment by gaenseklein** [comment]
armé base de datos, entrada, subir gifs como gifs, sobrevista en el dash y entrada en template frontpage.js. falta borrar publicidad. 
la publicidad se muestra desde la mañana del dia eligido en inicio hasta la noche del dia eligido en fin. 
asi si quieres solo en un dia lo eliges este dia como inicio y fin. si quieres de lunes hasta viernes incluido eliges lunes como inicio y viernes como fin.

**Comment by javierllugany** [comment]
agregué boton para eliminar publicidad
