### ISSUE TITLE
logos de redes para compartir noticias

### ISSUE THREAD

**Issue by javierllugany** [gaenseklein/comecuco#13]
posibilidad de compartir las noticias en las redes poniendo los logos de las redes abajo de cada noticia

**Comment by gaenseklein** [comment]
heise escribió una biblioteca javascript para eso:
https://github.com/heiseonline/shariff

el tema que no me gusta es que tiene mucha dependencia. pero ahi se ve en "demo" muchas links que podemos usar como ejemplo y generarlo por nuestro mismo:
http://heiseonline.github.io/shariff/

tenemos que eligir cual de los opciones quieremos.

**Comment by gaenseklein** [comment]
- telegram: https://t.me/share/url?url=http%3A%2F%2Fwww.heise.de%2F
- threema: threema://compose?text=Demonstration%3A%20Shariff%20-%20heise%20online%20http%3A%2F%2Fwww.heise.de%2F
- whatsapp: whatsapp://send?text=Demonstration%3A%20Shariff%20-%20heise%20online%20http%3A%2F%2Fwww.heise.de%2F
- diaspora: https://share.diasporafoundation.org/?url=http%3A%2F%2Fwww.heise.de%2F&title=Demonstration%3A%20Shariff%20-%20heise%20online
- facebook: https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fwww.heise.de%2F
- reddit: https://reddit.com/submit?url=http%3A%2F%2Fwww.heise.de%2F&title=Demonstration%3A%20Shariff%20-%20heise%20online
- tumblr: http://tumblr.com/widgets/share/tool?canonicalUrl=http%3A%2F%2Fwww.heise.de%2F
- flattr: https://flattr.com/submit/auto?title=Demonstration%3A%20Shariff%20-%20heise%20online&description=&category=text&user_id=example&url=http%3A%2F%2Fwww.heise.de%2F

los demas nunca escuché o son de rusia (vk). tambien tienen "imprimir" y que ademas podemos ofrecer sea "mail" (que abre thunderbird con un correo nuevo con subject y body)

**Comment by javierllugany** [comment]
no me funciona el logo de whatsap para compartir.... los otros logos si andan
