### ISSUE TITLE
se puede visualizar un contabilizador de audiencia del streaming?

### ISSUE THREAD

**Issue by javierllugany** [gaenseklein/comecuco#16]

**Comment by gaenseklein** [comment]
si, pero no le recomiendo. si quieren ver cuantas audiencias tienen actual pueden usar la pagina del streaming: 
https://comecuco.org:9000

**Comment by javierllugany** [comment]
y porque no lo recomiendas? (pregunto para saber nomás)

**Comment by gaenseklein** [comment]
porque no es un numero que sirve para algo, produce "ruido" no mas.
