### ISSUE TITLE
que noticias van a la seccion "Produccions colectivas"?

### ISSUE THREAD

**Issue by javierllugany** [gaenseklein/comecuco#17]
La autoría "COMECUCO" no tiene que definir que la noticia vaya a "Producciones Colectivas"... debería haber otro filtro

**Comment by gaenseklein** [comment]
ahora es: 
tipo: noticia, autor: "comecuco". 
no es por ejemplo resumen semanal ni capitulo de una columna. 
si quieren otro filtro tenemos que incorporarlo. una checkbox en el formulario mas u otro/cuarto tipo?

**Comment by gaenseklein** [comment]
tipo

**Comment by javierllugany** [comment]
agregué en editNoticia.html otra opcion de autoria: "Comecuco Producción Colectiva", y en templates/forms/noticia.js tambien agregué eso....... faltaria que con esa opcion de autor la noticia no vaya a la calesita y si vaya a la seccion Producciones Colectivas
