### ISSUE TITLE
archivo comecuco... como se actualiza?

### ISSUE THREAD

**Issue by javierllugany** [gaenseklein/comecuco#18]
como hacer para que se integren al archivo las noticias subidas en el periodo que va desde el apagon comecuco (el dia que se subió a prueba la nueva pagina) y la fecha en que la nueva pagina quede publica y activa

**Comment by gaenseklein** [comment]
es manualmente de mi. hay un script que puedo correr y le saca de la pagina actual

**Comment by javierllugany** [comment]
OK
