### ISSUE TITLE
habilitar posibilidad de corregir una noticia ya cargada, para que sea columna, o resumen 

### ISSUE THREAD

**Issue by javierllugany** [gaenseklein/comecuco#19]

**Comment by gaenseklein** [comment]
lo probe ahora con la ultima noticia y lo puedo cambiar a resumen y volver a ser noticia sin problemas. para ser capitulo de una columna hay que crear una columna primera. no es posible ni va a ser posible cambiarlo de noticia/capitulo/resumen a ser una columna ni al revez. lo ciero por ahora. si no funciona abren un bug con una descripcion mas clara que y cuando no ha funcionado.
