### ISSUE TITLE
que no todas las noticias suban automaticamente al carrusel

### ISSUE THREAD

**Issue by javierllugany** [gaenseklein/comecuco#2]
Que se pueda crear una noticia que al cargarla no vaya al carrusel (pagina principal) y vaya directo a la página de noticias de cada medio

**Comment by gaenseklein** [comment]
quieren otro tipo de noticias? o un checkbox "pagina principal"?

**Comment by gaenseklein** [comment]
checkbox sea

**Comment by javierllugany** [comment]
hecho el checkbox
