### ISSUE TITLE
que las fotos ocupen el mismo tamaño en el diseño del frontpage

### ISSUE THREAD

**Issue by javierllugany** [gaenseklein/comecuco#24]
la opcion podría ser que la pagina adapte y estandarice el tamaño de las fotos al cargar las fotos...?

**Comment by gaenseklein** [comment]
pues hay dos formas de solucionarlo. uno sea irse por el lado del servidor y enchiquear/enlargear el foto 'fisicamente' y guardardlo con ese tamaño. 
otro sea por lado del css - esa solucion me gustaria mejor. ya estuve haciendo intento de eso pero no lo guarde... a ver.

**Comment by gaenseklein** [comment]
lo cambie la calecita (de eso se habla creo yo) 
pero lo cambié que el tamaño del bloque de la calecita siempre esta igual y el imagen ocupa lo mas espacio posible. 
asi no hay ruptuacion en el ritmo (movimiento abajo/arriba) cuando llega una noticia con titulo largo (mas que una linea)

**Comment by gaenseklein** [comment]
ah no, las otros fotos ni tampoco estan iguales... maldicion

**Comment by gaenseklein** [comment]
lo hice ahora con la misma tecnica para los 2 grandes. los chiquitos tienen ahora un align-self: center. 
el tema es siempre cuando lo haces que el imagen debe ser un fijo tamaño que pierdes informaciones si el aspecto no es igual. 
o lo estrechas un imagen porque cambio el aspecto - que distorte el imagen. (personas gordas o flacas por ejemplo)
por eso eligi "cover" que ocupa todo el espacio y corta lo que sobrepasa. con "contain" se produce espacio libre (arriba/abajo o izquierda/derecha) - que era que no les gusta. asi eligi cover con lo que significa.
