### ISSUE TITLE
se pueden ir intercalando los datos del clima de dos o mas localidades?

### ISSUE THREAD

**Issue by javierllugany** [gaenseklein/comecuco#25]

**Comment by gaenseklein** [comment]
hay que chequear que profundo son los datos. ahora les saco para mendoza cerca capital. si el lugar es bastante lejo de eso y si hay diferentes datos del provedor si, sea posible. escribame un lugar con longitud/langitud (de google-maps o openstreetmaps lo puedes encontrar) y chequeo si hay datos diferentes o si el provedor sirve los mismos datos.

**Comment by javierllugany** [comment]
Ciudad de San Luis: -33.28788008543451, -66.3306103440347
Ciudad de San Juan: -31.541653230127974, -68.5306317190065
Las Vegas, Potrerillos Mendoza: -33.00798428623082, -69.2760358135036
El Retamo, Lavalle, Mendoza: -32.455505539285895, -67.37721510122489

**Comment by gaenseklein** [comment]
parece que son distintos... lo implementé
