### ISSUE TITLE
las publicidades no se ven enel dash de mozilla firefox

### ISSUE THREAD

**Issue by javierllugany** [gaenseklein/comecuco#27]
en el Inspector encontré que tenia display none, si lo anulo aparece el sector de publicidades... mirá las dos capturas... se desconfigura alguna otra cosa si anulamos ese display? igual tampoco entendí en que archivo está ese display none.... 

![Captura de pantalla 1](https://user-images.githubusercontent.com/91728698/195720802-1eb3b0c5-ebd6-45dd-9184-20a931ea3d7a.png)
![Captura de pantalla 2](https://user-images.githubusercontent.com/91728698/195720796-8125f7cc-655c-4897-8fe7-595dd764ae48.png)

**Comment by gaenseklein** [comment]
lol

no es un bug - es un feature! 

el feature me parece que es un plugin de firefox. no lo puedo ver la totalidad de la regla que dice "display:none" pero seguro que hay algo como ".publicidades" aldentro. Es un filtro de spam de tu firefox que te oculte publicidades y piensa que ese bloque son publicidades (aun su nombre) y por eso lo oculto (con !important ademas que dice como "ese regla sobreescribe todos reglas que no tienen !important aunque sean más concreto y por eso más alto en la jerarquia). 

lo puedo corregir en que lo pongo otro nombre para que tu filtro no le encuentre mas o simplemente lo digas a tu filtro algo como "en comecuco.org no filtras nada" o "apagado en comecuco.org".

**Comment by gaenseklein** [comment]
p.s.: no es de firefox por su mismo, es de un plugin que estas usando. en mi firefox se muestra sin problemas

**Comment by javierllugany** [comment]
ahi elimine un complemento que hablaba de protection y ya puedo ver el bloque de publicidad... joyaaa!
