### ISSUE TITLE
Columnas: no se ve la imagen en la pagina de inicio 

### ISSUE THREAD

**Issue by javierllugany** [gaenseklein/comecuco#6]

**Comment by javierllugany** [comment]
a uno le pasó que si pudo subir fotos jpg, pero las fotos jpeg no las pudo cargar

**Comment by javierllugany** [comment]
ésta es la issue de que no funciona algo en el frontpage porque no se ven las imagenes de las columnas

**Comment by gaenseklein** [comment]
no funciono porque no han subido un imagen al capitulo actual
