### ISSUE TITLE
Que se pueda borrar una noticia publicada

### ISSUE THREAD

**Issue by javierllugany** [gaenseklein/comecuco#7]

**Comment by gaenseklein** [comment]
la funcion ya esta aldentro, faltan los links. donde le podemos? en la pagina de edicion del articulo? o en la sobrevista/dash? 

si quieres borrar una noticia ya lo puedes en que cambias la url a /user/borrar/noticia/id-de-la-noticia (entrar un "borrar/" entre /user y /noticia/)
